### ISSUE TITLE
Error handling request

### ISSUE THREAD

**Issue by luislhl** [HathorNetwork/tx-mining-service#63]
```
Traceback (most recent call last):
 File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 314, in data_received
   messages, upgraded, tail = self._request_parser.feed_data(data)
 File "aiohttp/_http_parser.pyx", line 546, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadHttpMessage: 400, message='invalid constant string'
```

We should investigate what causes this and treat the error

**Comment by msbrogli** [comment]
It might be related to this open issue: https://github.com/aio-libs/aiohttp/issues/3641
